create extension if not exists pgcrypto;

create table if not exists requests (
  id uuid primary key default gen_random_uuid(),
  tracking_number text unique not null,
  title text not null,
  description text,
  category text not null,
  address text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table if not exists announcements (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

insert into announcements (type, title, body)
values
  (
    'urgent',
    'Water Main Maintenance — West Evesham Ave',
    'Scheduled water service interruption on West Evesham Ave between Holly and Magnolia Ave, Thursday March 26 from 9AM–2PM. Residents may experience reduced pressure.'
  ),
  (
    'event',
    'Borough Council Meeting — April 7th',
    'The next regular council meeting will be held Monday, April 7th at 7:00 PM in Borough Hall. Public comment period begins at 7:30 PM. All residents welcome.'
  ),
  (
    'info',
    'Spring Bulk Trash Pickup Schedule',
    'Spring bulk trash pickup begins the week of April 14th. Items must be placed curbside by 7AM on your scheduled day. Electronics and hazardous materials are not accepted.'
  );

insert into requests (tracking_number, title, description, category, address, status)
values
  (
    'MGN-0041',
    'Pothole at Magnolia Ave & 3rd St',
    'Large pothole near intersection, approximately 12" wide. Hazardous to vehicles.',
    'Roads & Infrastructure',
    'Magnolia Ave & 3rd St',
    'progress'
  ),
  (
    'MGN-0040',
    'Streetlight Out — Holly Ave',
    'Streetlight in front of 214 Holly Ave has been out for 3 days.',
    'Utilities & Lighting',
    '214 Holly Ave',
    'open'
  ),
  (
    'MGN-0039',
    'Abandoned vehicle — Oak St',
    'Silver sedan with no plates parked in front of 88 Oak St for over 2 weeks.',
    'Noise & Safety',
    '88 Oak St',
    'resolved'
  );
  -- ==========================================
-- ADDED: AUDIT LOGS TABLE & POLICIES original above | additional below
-- ============================================
create table public.audit_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,      -- e.g., 'announcement_created'
  actor_id uuid not null,        -- references auth.users
  timestamp timestamptz default now(),
  related_record_id text,        -- ID of the request or announcement
  metadata jsonb                 -- flexible field for event details
);

-- Enable RLS for data protection
alter table public.audit_logs enable row level security;

-- Policy: Only authenticated staff can read their own logs (or all logs)
create policy "Staff can view all audit logs" on public.audit_logs
  for select to authenticated using (true);